# Boston locations
# sell

* broadst45
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 45 Broad St"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.358180"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.054380"

* courtst63
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 45 Court St"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.359368"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.059191"

* schoolst27
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 27 School St"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.357742"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.059052"

* beaconst65
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 65-66 Beacon St"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.356350"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.069321"


# Boston locations
# intake

* thompsonsq1
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 1 Thomson Square"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.374572"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.062986"

* boylstonst62
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 62 Boylston St"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.352116"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.064423"

* statest84
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 84 State Street"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.359154"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.055573"

* cambridgest222
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 222 Cambridge St"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="Boston"
export POT_FUNCTION_APP_LOCATION_LATITUDE="42.361042"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-71.066513"


# London locations
# sell

* goodgest51
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 51-53 Goodge St"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.519108"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.136055"

* kingsway99
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 99 Kingsway"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.516396"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.120133"

* mephamst12
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 12 A Mepham Street"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.503155"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.113271"

* newbridgest30
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop 30-34A New Bridge Street"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.512573"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.103990"


# London locations
# intake

* longacre55
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 55-56 Long Acre"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.512405"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.127450"

* boroughhighst223
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 223-227 Borough High Street"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.501034"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.093202"

* wandsworthrd62
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 62 Wandsworth Road"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.481529"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.127924"

* basilst25
export POT_FUNCTION_APP_DESCRIPTION="Warehouse 25 Basil St"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="London"
export POT_FUNCTION_APP_LOCATION_LATITUDE="51.498737"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="-0.161783"


# Shanghai location
# sale

* linyinorthrd
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop No.200 Linyi North Road"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="Shanghai"
export POT_FUNCTION_APP_LOCATION_LATITUDE="31.205091"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="121.517975"

* huaihaimiddlerd935
export POT_FUNCTION_APP_DESCRIPTION="Coffee Shop Huaihai Middle Road 935"
export POT_FUNCTION_APP_TYPE="sell"
export POT_FUNCTION_APP_LOCATION_NAME="Shanghai"
export POT_FUNCTION_APP_LOCATION_LATITUDE="31.216913"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="121.459732"


# Shanghai location
# intake

* yananeastrd618
export POT_FUNCTION_APP_DESCRIPTION="Warehouse Yanan East Road No.618"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="Shanghai"
export POT_FUNCTION_APP_LOCATION_LATITUDE="31.229914"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="121.480026"

* xujiahuird618
export POT_FUNCTION_APP_DESCRIPTION="Warehouse Xujiahui Road No.618"
export POT_FUNCTION_APP_TYPE="intake"
export POT_FUNCTION_APP_LOCATION_NAME="Shanghai"
export POT_FUNCTION_APP_LOCATION_LATITUDE="31.207479"
export POT_FUNCTION_APP_LOCATION_LONGITUDE="121.468803"


